#!/usr/bin/env node
const program = require('commander')
const server = require('../server')
const debug = require('debug')

let modeValue

program
  .arguments('<mode>')
  .option('-p, --port <port>', 'Server port')
  .option('-c, --cluster <cluster>', 'Number of cluster')
  .option('-l, --lang <lang>', 'Default server lang')
  .option('--db_port <dbPort>', 'Database port')
  .option('--db_host <dHhost>', 'Database host')
  .option('--db_name <dbName>', 'Database name')
  .option('--db_username <dbUsername>', 'Database username')
  .option('--db_password <dbPassword>', 'Database password')
  .option('--console_log', 'Log in terminal')
  .description('Start server')
  .action((mode, options) => {
    modeValue = mode

    if (mode !== 'dev' && mode !== 'prod') {
      console.log(`Unknown mode ${mode}. Try with dev or prod.`)
      return process.exit(1)
    }

    debug.disable()
    server.run(mode, process.env.HEARTH_SERVER_PATH, options, (err) => {
      if (err) {
        console.log('An error occured while running server: ', err)
        return process.exit(1)
      }
    })
  })
  .parse(process.argv)

if (typeof modeValue === 'undefined') {
  console.error('You must specify mode `dev` or `prod`.')
  process.exit(1)
}
